#指定服务的名字
spring:
  application:
    name: itoken-eureka

#端口号
server:
  port: 8761

eureka:
  instance:
    hostname: localhost #eureka的地址
  client:
    registerWithEureka: false #这两个配置为false时是服务端，否则为客户端
    fetchRegistry: false
    serviceUrl: #设置eureka地址
      defaultZone: http://localhost:8761/eureka/
